### ISSUE TITLE
using Route name is not Working

### ISSUE THREAD

**Issue by mobarokhossen** [firoz-ahmad-likhon/codeigniter-role-base-access-control#2]
Hi,

I worked user role and permission there is a problem in route access. When i am using routing this route_access is not working. Is there any way to access using route name. Because I am using route name. Please help me. 

Sample: $route['role/add'] = 'admin/add_role';

Thanks

**Comment by firoz-ahmad-likhon** [comment]
We need to develop a method to support the routing name. I will do it asap.

**Comment by mobarokhossen** [comment]
Thanks. I already have done this.
